### ISSUE TITLE
Total value requirement not met.

### ISSUE THREAD

**Issue by Jason-MacDonald** [Jason-MacDonald/SDV701-Project#1]
**Location:**
Wiki - Application Screen Shots (WinForm Application)

**Issue**:
The projects requirement for **_total value of all current orders_** has not been met.

**Suggested Fix:**
Update screenshot to indicate total value of all current orders.

**Additional Notes:**
Only required for WinForm Application.

**Comment by Jason-MacDonald** [comment]
The projects requirement for total value of all current orders has been added to the [Screen Shots](https://github.com/Jason-MacDonald/SDV701-Project/wiki/Screen-Shots).

**Comment by MatthiasNZ** [comment]
Nice one, Jason.  I can see you are enjoying this way of project management!  You wish to share your experience with classmates if you like.  I think some folk's work habits need improvement ;-)
I'm still not quite at home with GitHub, I still need to get used to its navigation paradigm.  Like when I'm looking at a closed issue (currently all your issues are closed), and want to see another (closed) issue, I click on _Issues_, and see nothing, then move to _Closed_ in order to move _between_ closed issues.  Maybe there's a more efficient way...

**Comment by Jason-MacDonald** [comment]
> Like when I'm looking at a closed issue (currently all your issues are closed), and want to see another (closed) issue, I click on Issues, and see nothing, then move to Closed in order to move between closed issues. Maybe there's a more efficient way...

Ah yes, I see. Using the _is:issue_ filter brings up both open and closed issues but after a quick online search it doesn't look like there is any way to change the default. 

I see a [feature request has been added](https://github.community/t5/How-to-use-Git-and-GitHub/Can-you-change-the-default-issue-filter-options-for-a-project/td-p/10424).
